class_name CharacterPortraitHolder
extends Control


@onready var characterBackgroundPanel: Panel = $MarginContainer/characterBackgroundPanel
@onready var characterPortraitImageTextureRect: TextureRect = $MarginContainer/characterContariner_VBoxContainer/portraitMarginContainer/characterPortraitTextureRect
@onready var characterNameLabel: Label = $MarginContainer/characterContariner_VBoxContainer/characterNameLabel

@onready var topLeftCornerSelectionComponent: CornerSelectionComponent = $MarginContainer/characterContariner_VBoxContainer/portraitMarginContainer/selectionMarkContainer_VBoxContainer2/topSelections_HBoxContainer/topLeftCornerSelectionComponent
@onready var topRightCornerSelectionComponent: CornerSelectionComponent = $MarginContainer/characterContariner_VBoxContainer/portraitMarginContainer/selectionMarkContainer_VBoxContainer2/topSelections_HBoxContainer/topRightCornerSelectionComponent
@onready var bottomLeftCornerSelectionComponent: CornerSelectionComponent = $MarginContainer/characterContariner_VBoxContainer/portraitMarginContainer/selectionMarkContainer_VBoxContainer2/bottomSelections_HBoxContainer/bottomLeftCornerSelectionComponent
@onready var bottomRightCornerSelectionComponent: CornerSelectionComponent = $MarginContainer/characterContariner_VBoxContainer/portraitMarginContainer/selectionMarkContainer_VBoxContainer2/bottomSelections_HBoxContainer/bottomRightCornerSelectionComponent
